### ISSUE TITLE
incorrect path in flashall.bat 

### ISSUE THREAD

**Issue by martinkronberg** [ostroproject/ostro-os#62]
the Ostro image for Intel Edison has typos in the paths in flashall.bat: 

"%BASE_DIR%edison-image-edison.hddimg" should be "%BASE_DIR%ostro-image-edison.hddimg"

"%BASE_DIR%edison-image-edison.update.hddimg" should be "%BASE_DIR%ostro-image-edison.update.hddimg"

"%BASE_DIR%edison-image-edison.ext4" should be "%BASE_DIR%ostro-image-edison.ext4"

**Comment by gvancuts** [comment]
@jlaako can you take a look?

**Comment by jlaako** [comment]
Yes, I'm looking into this. However, it is not as simple as changing the image name, since we produce various images with different names. I need to modify it to functionally match the Linux script.

**Comment by jlaako** [comment]
Fixed in https://github.com/ostroproject/meta-ostro-bsp/pull/29

**Comment by ralf-graefe** [comment]
The same applies to the FlashEdison.json which is used by the Phone Flash tool on Windows.

**Comment by pohly** [comment]
@jlaako please not that @ralf-graefe pointed out that problem still exists elsewhere (FlashEdison.json).
